"""
标签翻译模块（重构版）

将 DeepDanbooru 的英文标签翻译成中文

内建 400+ 常见标签的高质量中文翻译字典，覆盖绝大多数 AI 打标结果。
支持外部翻译文件扩展和缓存。
"""

import json
import os
from typing import Dict, Optional
import logging
import re

logger = logging.getLogger(__name__)

# ============================================================
# 内建翻译字典：覆盖 DeepDanbooru 最常用的 400+ 标签
# ============================================================
BUILTIN_TRANSLATIONS: Dict[str, str] = {
    # === 人物数量 ===
    "1girl": "1个女孩",
    "2girls": "2个女孩",
    "3girls": "3个女孩",
    "4girls": "4个女孩",
    "5girls": "5个女孩",
    "6+girls": "6个以上女孩",
    "multiple_girls": "多个女孩",
    "1boy": "1个男孩",
    "2boys": "2个男孩",
    "3boys": "3个男孩",
    "4boys": "4个男孩",
    "5boys": "5个男孩",
    "6+boys": "6个以上男孩",
    "multiple_boys": "多个男孩",
    "solo": "单人",
    "solo_focus": "单人特写",
    "couple": "情侣",
    "group": "群体",
    "crowd": "人群",
    "no_humans": "无人",
    "1other": "1个其他角色",

    # === 发型 ===
    "long_hair": "长发",
    "short_hair": "短发",
    "medium_hair": "中长发",
    "very_long_hair": "超长发",
    "absurdly_long_hair": "极长发",
    "twintails": "双马尾",
    "ponytail": "马尾辫",
    "twin_braids": "双辫子",
    "braid": "辫子",
    "side_braid": "侧辫",
    "french_braid": "法式辫",
    "braided_ponytail": "辫子马尾",
    "single_braid": "单辫",
    "pigtails": "双马尾",
    "hair_bun": "丸子头",
    "double_bun": "双丸子头",
    "side_ponytail": "侧马尾",
    "low_ponytail": "低马尾",
    "high_ponytail": "高马尾",
    "low_twintails": "低双马尾",
    "short_twintails": "短双马尾",
    "bangs": "刘海",
    "blunt_bangs": "齐刘海",
    "side_bangs": "侧刘海",
    "swept_bangs": "斜刘海",
    "parted_bangs": "分开刘海",
    "hair_over_one_eye": "遮眼发",
    "hair_over_eyes": "遮眼",
    "hair_between_eyes": "眉间发",
    "sidelocks": "鬓发",
    "ahoge": "呆毛",
    "antenna_hair": "触角发",
    "messy_hair": "凌乱发型",
    "wavy_hair": "波浪发",
    "curly_hair": "卷发",
    "straight_hair": "直发",
    "drill_hair": "公主卷",
    "twin_drills": "双公主卷",
    "bob_cut": "波波头",
    "pixie_cut": "精灵短发",
    "hime_cut": "公主切",
    "hair_flaps": "翘发",
    "floating_hair": "飘发",
    "hair_spread_out": "散开的头发",
    "wet_hair": "湿发",
    "hair_ribbon": "发带",
    "hairband": "发箍",
    "hairclip": "发夹",
    "hair_ornament": "发饰",
    "hair_flower": "发花",
    "hair_bow": "发蝴蝶结",
    "hair_tie": "扎发绳",
    "scrunchie": "发圈",
    "head_wings": "头翼",

    # === 发色 ===
    "blonde_hair": "金发",
    "brown_hair": "棕发",
    "black_hair": "黑发",
    "blue_hair": "蓝发",
    "red_hair": "红发",
    "pink_hair": "粉发",
    "purple_hair": "紫发",
    "green_hair": "绿发",
    "white_hair": "白发",
    "silver_hair": "银发",
    "grey_hair": "灰发",
    "gray_hair": "灰发",
    "orange_hair": "橙发",
    "aqua_hair": "水蓝发",
    "light_brown_hair": "浅棕发",
    "light_blue_hair": "浅蓝发",
    "light_purple_hair": "浅紫发",
    "multicolored_hair": "多色发",
    "two-tone_hair": "双色发",
    "gradient_hair": "渐变发",
    "streaked_hair": "挑染发",

    # === 眼睛 ===
    "blue_eyes": "蓝色眼睛",
    "red_eyes": "红色眼睛",
    "brown_eyes": "棕色眼睛",
    "green_eyes": "绿色眼睛",
    "purple_eyes": "紫色眼睛",
    "yellow_eyes": "黄色眼睛",
    "pink_eyes": "粉色眼睛",
    "orange_eyes": "橙色眼睛",
    "black_eyes": "黑色眼睛",
    "white_eyes": "白色眼睛",
    "grey_eyes": "灰色眼睛",
    "gray_eyes": "灰色眼睛",
    "aqua_eyes": "水蓝眼睛",
    "golden_eyes": "金色眼睛",
    "heterochromia": "异色瞳",
    "multicolored_eyes": "多色瞳",
    "closed_eyes": "闭眼",
    "half-closed_eyes": "半闭眼",
    "one_eye_closed": "单眼闭合",
    "glowing_eyes": "发光眼睛",
    "empty_eyes": "空洞眼神",
    "tsurime": "吊眼",
    "tareme": "垂眼",
    "slit_pupils": "竖瞳",
    "symbol-shaped_pupils": "特殊瞳孔",
    "heart-shaped_pupils": "爱心瞳",
    "star-shaped_pupils": "星形瞳",

    # === 表情 ===
    "smile": "微笑",
    "open_mouth": "张嘴",
    "closed_mouth": "闭嘴",
    "grin": "咧嘴笑",
    "blush": "脸红",
    "frown": "皱眉",
    "angry": "生气",
    "crying": "哭泣",
    "tears": "眼泪",
    "surprised": "惊讶",
    "nervous": "紧张",
    "embarrassed": "害羞",
    "smug": "得意",
    "serious": "严肃",
    "expressionless": "无表情",
    "sad": "悲伤",
    "happy": "开心",
    "pout": "撅嘴",
    "tongue": "伸舌",
    "tongue_out": "吐舌头",
    ":d": "大笑",
    ":o": "惊讶",
    ":3": "猫嘴",
    "^^": "眯眼笑",
    ";d": "眨眼笑",
    "^_^": "眯眼笑",
    ">_<": "紧闭双眼",
    "wink": "眨眼",
    "light_smile": "淡笑",
    "evil_smile": "邪笑",
    "naughty_face": "调皮表情",
    "shy": "害羞",
    "scared": "害怕",
    "frustrated": "沮丧",
    "confused": "困惑",
    "sweat": "流汗",
    "sweatdrop": "汗滴",

    # === 身体特征 ===
    "breasts": "胸部",
    "small_breasts": "小胸",
    "medium_breasts": "中等胸部",
    "large_breasts": "大胸",
    "huge_breasts": "巨胸",
    "flat_chest": "平胸",
    "cleavage": "乳沟",
    "navel": "肚脐",
    "collarbone": "锁骨",
    "midriff": "露腰",
    "thighs": "大腿",
    "thigh_gap": "大腿缝隙",
    "wide_hips": "宽臀",
    "narrow_waist": "细腰",
    "slim": "纤细",
    "muscular": "肌肉",
    "abs": "腹肌",
    "armpits": "腋下",
    "bare_shoulders": "露肩",
    "bare_arms": "露臂",
    "bare_legs": "露腿",
    "bare_back": "露背",
    "bare_feet": "赤脚",
    "barefoot": "赤脚",
    "feet": "脚",
    "toes": "脚趾",
    "legs": "腿",
    "arms": "手臂",
    "hand_up": "举手",
    "hands_up": "双手举起",
    "arms_up": "双臂举起",
    "hand_on_hip": "手叉腰",
    "hands_on_hips": "双手叉腰",
    "hand_on_own_chest": "手放胸口",
    "hand_to_own_mouth": "手捂嘴",
    "hand_on_own_face": "手托脸",
    "chin_rest": "托腮",
    "pointy_ears": "尖耳朵",
    "animal_ears": "兽耳",
    "cat_ears": "猫耳",
    "fox_ears": "狐耳",
    "rabbit_ears": "兔耳",
    "dog_ears": "犬耳",
    "wolf_ears": "狼耳",
    "horse_ears": "马耳",
    "tail": "尾巴",
    "cat_tail": "猫尾",
    "fox_tail": "狐狸尾巴",
    "wings": "翅膀",
    "angel_wings": "天使翅膀",
    "demon_wings": "恶魔翅膀",
    "bat_wings": "蝙蝠翅膀",
    "feathered_wings": "羽翼",
    "horns": "角",
    "demon_horns": "恶魔角",
    "halo": "光环",
    "fang": "虎牙",
    "fangs": "虎牙",
    "mole": "痣",
    "freckles": "雀斑",
    "scar": "疤痕",
    "tattoo": "纹身",

    # === 服装 ===
    "dress": "连衣裙",
    "shirt": "衬衫",
    "skirt": "裙子",
    "shorts": "短裤",
    "pants": "裤子",
    "jacket": "夹克",
    "coat": "外套",
    "hoodie": "卫衣",
    "sweater": "毛衣",
    "vest": "背心",
    "cardigan": "开衫",
    "blazer": "西装外套",
    "suit": "西装",
    "cape": "披风",
    "cloak": "斗篷",
    "robe": "长袍",
    "apron": "围裙",
    "uniform": "制服",
    "school_uniform": "校服",
    "sailor_uniform": "水手服",
    "serafuku": "水手服",
    "military_uniform": "军装",
    "maid": "女仆",
    "maid_headdress": "女仆头饰",
    "maid_apron": "女仆围裙",
    "armor": "盔甲",
    "kimono": "和服",
    "japanese_clothes": "日式服装",
    "chinese_clothes": "中式服装",
    "hakama": "袴",
    "yukata": "浴衣",
    "bikini": "比基尼",
    "swimsuit": "泳装",
    "one-piece_swimsuit": "连体泳衣",
    "bikini_top": "比基尼上衣",
    "bikini_bottom": "比基尼下装",
    "lingerie": "内衣",
    "bra": "胸罩",
    "underwear": "内衣裤",
    "panties": "内裤",
    "undershirt": "汗衫",
    "crop_top": "露脐上衣",
    "tank_top": "吊带背心",
    "halterneck": "挂脖",
    "off_shoulder": "露肩装",
    "off-shoulder_dress": "露肩连衣裙",
    "strapless": "无肩带",
    "sleeveless": "无袖",
    "short_sleeves": "短袖",
    "long_sleeves": "长袖",
    "wide_sleeves": "宽袖",
    "detached_sleeves": "分离袖",
    "puffy_sleeves": "泡泡袖",
    "frills": "褶边",
    "frilled_dress": "褶边连衣裙",
    "frilled_skirt": "褶边裙",
    "lace": "蕾丝",
    "lace_trim": "蕾丝边",
    "ribbon": "丝带",
    "bow": "蝴蝶结",
    "bowtie": "领结",
    "necktie": "领带",
    "collar": "衣领",
    "choker": "项圈",
    "necklace": "项链",
    "scarf": "围巾",
    "ascot": "领巾",
    "gloves": "手套",
    "elbow_gloves": "长手套",
    "fingerless_gloves": "露指手套",
    "thighhighs": "过膝袜",
    "kneehighs": "及膝袜",
    "socks": "短袜",
    "pantyhose": "连裤袜",
    "fishnet": "网袜",
    "fishnet_pantyhose": "网状连裤袜",
    "garter_straps": "吊带袜",
    "garter_belt": "吊袜带",
    "black_thighhighs": "黑色过膝袜",
    "white_thighhighs": "白色过膝袜",
    "striped_thighhighs": "条纹过膝袜",
    "boots": "靴子",
    "high_heels": "高跟鞋",
    "shoes": "鞋子",
    "sneakers": "运动鞋",
    "loafers": "乐福鞋",
    "sandals": "凉鞋",
    "mary_janes": "玛丽珍鞋",
    "knee_boots": "及膝靴",
    "thigh_boots": "过膝靴",
    "hat": "帽子",
    "beret": "贝雷帽",
    "witch_hat": "女巫帽",
    "top_hat": "礼帽",
    "sun_hat": "遮阳帽",
    "straw_hat": "草帽",
    "baseball_cap": "棒球帽",
    "mob_cap": "蕾丝帽",
    "crown": "皇冠",
    "tiara": "冠冕",
    "headband": "头带",
    "glasses": "眼镜",
    "sunglasses": "太阳镜",
    "goggles": "护目镜",
    "mask": "面具",
    "mouth_mask": "口罩",
    "earrings": "耳环",
    "bracelet": "手镯",
    "ring": "戒指",
    "anklet": "脚链",
    "watch": "手表",
    "backpack": "背包",
    "bag": "包",
    "handbag": "手提包",
    "belt": "腰带",
    "zipper": "拉链",
    "buttons": "纽扣",
    "pleated_skirt": "百褶裙",
    "miniskirt": "迷你裙",
    "long_skirt": "长裙",
    "white_dress": "白色连衣裙",
    "black_dress": "黑色连衣裙",
    "red_dress": "红色连衣裙",
    "blue_dress": "蓝色连衣裙",
    "pink_dress": "粉色连衣裙",
    "white_shirt": "白色衬衫",
    "black_shirt": "黑色衬衫",
    "t-shirt": "T恤",
    "plaid": "格子花纹",
    "plaid_skirt": "格子裙",
    "striped": "条纹",
    "polka_dot": "波点",

    # === 姿势/动作 ===
    "sitting": "坐着",
    "standing": "站着",
    "lying": "躺着",
    "kneeling": "跪着",
    "walking": "走路",
    "running": "奔跑",
    "jumping": "跳跃",
    "flying": "飞翔",
    "floating": "漂浮",
    "crouching": "蹲着",
    "squatting": "蹲下",
    "leaning": "靠着",
    "leaning_forward": "前倾",
    "leaning_back": "后仰",
    "on_back": "仰躺",
    "on_side": "侧躺",
    "on_stomach": "趴着",
    "hugging": "拥抱",
    "hug": "拥抱",
    "holding": "拿着",
    "holding_hands": "牵手",
    "reaching": "伸手",
    "stretching": "伸懒腰",
    "dancing": "跳舞",
    "fighting": "战斗",
    "sleeping": "睡觉",
    "eating": "吃东西",
    "drinking": "喝东西",
    "reading": "阅读",
    "singing": "唱歌",
    "playing_instrument": "演奏乐器",
    "playing_guitar": "弹吉他",
    "playing_piano": "弹钢琴",
    "looking_at_viewer": "看向观众",
    "looking_away": "转头看别处",
    "looking_back": "回头看",
    "looking_up": "仰望",
    "looking_down": "低头看",
    "looking_to_the_side": "侧望",
    "from_above": "俯视",
    "from_below": "仰视",
    "from_behind": "背面视角",
    "from_side": "侧面视角",
    "facing_away": "背对",
    "back": "背影",
    "profile": "侧脸",
    "head_tilt": "歪头",
    "turned_head": "转头",
    "crossed_arms": "双臂交叉",
    "crossed_legs": "翘二郎腿",
    "legs_crossed": "翘二郎腿",
    "v": "V手势",
    "peace_sign": "V手势",
    "thumbs_up": "竖大拇指",
    "waving": "挥手",
    "salute": "敬礼",
    "fighting_stance": "战斗姿态",
    "spread_arms": "张开双臂",
    "arm_support": "手撑",
    "all_fours": "四肢着地",
    "wariza": "W坐姿",
    "seiza": "正坐",
    "indian_style": "盘腿坐",
    "yokozuwari": "侧坐",
    "leg_up": "抬腿",
    "legs_up": "双腿抬起",
    "leg_lift": "踢腿",
    "ass": "臀部",

    # === 视角/构图 ===
    "upper_body": "上半身",
    "lower_body": "下半身",
    "full_body": "全身",
    "portrait": "肖像",
    "close-up": "特写",
    "face": "脸部",
    "cowboy_shot": "牛仔镜头",
    "dutch_angle": "倾斜构图",
    "wide_shot": "广角镜头",
    "pov": "第一人称视角",
    "selfie": "自拍",
    "eye_focus": "聚焦眼睛",

    # === 背景/场景 ===
    "outdoors": "户外",
    "indoors": "室内",
    "sky": "天空",
    "cloud": "云",
    "clouds": "云彩",
    "night": "夜晚",
    "night_sky": "夜空",
    "sunset": "日落",
    "sunrise": "日出",
    "starry_sky": "星空",
    "moon": "月亮",
    "crescent_moon": "新月",
    "full_moon": "满月",
    "sun": "太阳",
    "sunlight": "阳光",
    "water": "水",
    "ocean": "海洋",
    "sea": "大海",
    "river": "河流",
    "lake": "湖泊",
    "waterfall": "瀑布",
    "rain": "雨",
    "snow": "雪",
    "snowing": "下雪",
    "cherry_blossoms": "樱花",
    "petals": "花瓣",
    "flower": "花",
    "flowers": "花朵",
    "rose": "玫瑰",
    "sunflower": "向日葵",
    "lotus": "莲花",
    "lily": "百合花",
    "tree": "树",
    "forest": "森林",
    "grass": "草地",
    "field": "田野",
    "garden": "花园",
    "mountain": "山",
    "mountains": "群山",
    "beach": "海滩",
    "city": "城市",
    "cityscape": "城市风景",
    "building": "建筑",
    "castle": "城堡",
    "ruins": "废墟",
    "classroom": "教室",
    "library": "图书馆",
    "bedroom": "卧室",
    "kitchen": "厨房",
    "bathroom": "浴室",
    "school": "学校",
    "church": "教堂",
    "shrine": "神社",
    "temple": "寺庙",
    "bridge": "桥",
    "street": "街道",
    "alley": "小巷",
    "rooftop": "屋顶",
    "window": "窗户",
    "balcony": "阳台",
    "stairs": "楼梯",
    "door": "门",
    "fence": "栅栏",
    "underwater": "水下",
    "space": "太空",
    "fantasy": "幻想",
    "simple_background": "简单背景",
    "white_background": "白色背景",
    "black_background": "黑色背景",
    "blue_background": "蓝色背景",
    "pink_background": "粉色背景",
    "gradient_background": "渐变背景",
    "grey_background": "灰色背景",
    "gray_background": "灰色背景",
    "blurry_background": "模糊背景",
    "blurry": "模糊",
    "depth_of_field": "景深",
    "bokeh": "散景",
    "lens_flare": "镜头光晕",
    "light_rays": "光线",
    "backlighting": "逆光",
    "shadow": "影子",
    "reflection": "倒影",
    "sparkle": "闪光",
    "glowing": "发光",
    "particle": "粒子",
    "light_particles": "光粒子",

    # === 物品/道具 ===
    "sword": "剑",
    "katana": "日本刀",
    "gun": "枪",
    "rifle": "步枪",
    "pistol": "手枪",
    "bow_(weapon)": "弓",
    "arrow": "箭",
    "wand": "魔杖",
    "staff": "法杖",
    "shield": "盾牌",
    "spear": "矛",
    "scythe": "镰刀",
    "axe": "斧头",
    "umbrella": "雨伞",
    "parasol": "阳伞",
    "fan": "扇子",
    "folding_fan": "折扇",
    "book": "书",
    "open_book": "打开的书",
    "phone": "手机",
    "smartphone": "智能手机",
    "cellphone": "手机",
    "camera": "相机",
    "food": "食物",
    "cake": "蛋糕",
    "candy": "糖果",
    "lollipop": "棒棒糖",
    "ice_cream": "冰淇淋",
    "doughnut": "甜甜圈",
    "cup": "杯子",
    "teacup": "茶杯",
    "mug": "马克杯",
    "wine_glass": "酒杯",
    "bottle": "瓶子",
    "tea": "茶",
    "coffee": "咖啡",
    "cigarette": "香烟",
    "microphone": "麦克风",
    "guitar": "吉他",
    "piano": "钢琴",
    "violin": "小提琴",
    "headphones": "耳机",
    "flag": "旗帜",
    "lantern": "灯笼",
    "candle": "蜡烛",
    "lamp": "灯",
    "mirror": "镜子",
    "clock": "钟",
    "key": "钥匙",
    "chain": "链子",
    "rope": "绳子",
    "chair": "椅子",
    "table": "桌子",
    "desk": "书桌",
    "bed": "床",
    "pillow": "枕头",
    "blanket": "毯子",
    "curtains": "窗帘",
    "carpet": "地毯",
    "stuffed_animal": "毛绒玩具",
    "stuffed_toy": "毛绒玩具",
    "teddy_bear": "泰迪熊",
    "doll": "玩偶",
    "ball": "球",
    "balloon": "气球",
    "gift": "礼物",
    "gift_box": "礼物盒",
    "letter": "信件",
    "envelope": "信封",
    "card": "卡片",
    "notebook": "笔记本",
    "pen": "笔",
    "pencil": "铅笔",
    "paintbrush": "画笔",
    "palette": "调色盘",
    "easel": "画架",
    "canvas": "画布",
    "bubble": "泡泡",
    "bubbles": "泡泡",
    "soap_bubbles": "肥皂泡",
    "air_bubble": "气泡",
    "water_drop": "水滴",
    "bubble_blowing": "吹泡泡",

    # === 动物 ===
    "cat": "猫",
    "dog": "狗",
    "bird": "鸟",
    "rabbit": "兔子",
    "fox": "狐狸",
    "wolf": "狼",
    "horse": "马",
    "dragon": "龙",
    "snake": "蛇",
    "fish": "鱼",
    "butterfly": "蝴蝶",
    "bat": "蝙蝠",
    "owl": "猫头鹰",
    "crow": "乌鸦",
    "dove": "鸽子",
    "deer": "鹿",
    "bear": "熊",
    "panda": "熊猫",
    "tiger": "老虎",
    "lion": "狮子",
    "whale": "鲸鱼",
    "dolphin": "海豚",
    "octopus": "章鱼",
    "jellyfish": "水母",
    "spider": "蜘蛛",
    "insect": "昆虫",
    "firefly": "萤火虫",
    "frog": "青蛙",

    # === 效果/技术 ===
    "monochrome": "黑白",
    "greyscale": "灰度",
    "sepia": "复古色调",
    "sketch": "素描",
    "lineart": "线稿",
    "watercolor_(medium)": "水彩",
    "oil_painting_(medium)": "油画",
    "pixel_art": "像素画",
    "chibi": "Q版",
    "realistic": "写实",
    "photorealistic": "照片级写实",
    "absurdres": "超高分辨率",
    "highres": "高分辨率",
    "incredibly_absurdres": "极超高分辨率",
    "masterpiece": "杰作",
    "best_quality": "最佳质量",
    "official_art": "官方图",
    "key_visual": "主视觉图",
    "manga": "漫画",
    "comic": "漫画",
    "4koma": "四格漫画",
    "traditional_media": "传统媒体",
    "digital_media_(artwork)": "数字艺术",
    "illustration": "插画",
    "transparent_background": "透明背景",
    "border": "边框",
    "motion_blur": "运动模糊",
    "speed_lines": "速度线",
    "motion_lines": "运动线",
    "chromatic_aberration": "色差",
    "film_grain": "胶片噪点",
    "halftone": "半色调",
    "colorful": "色彩丰富",
    "vibrant": "鲜艳",
    "dark": "暗色调",
    "bright": "明亮",
    "high_contrast": "高对比度",
    "soft_lighting": "柔和光线",
    "dramatic_lighting": "戏剧性光线",
    "volumetric_lighting": "体积光",
    "rim_lighting": "轮廓光",

    # === 其他常见标签 ===
    "original": "原创",
    "copyright_request": "版权请求",
    "artist_request": "画师请求",
    "bad_id": "旧链接",
    "bad_pixiv_id": "旧Pixiv链接",
    "translated": "已翻译",
    "commentary": "评论",
    "commentary_request": "评论请求",
    "character_request": "角色请求",
    "source_request": "出处请求",
    "revision": "修订版",
    "alternate_costume": "替换服装",
    "alternate_hairstyle": "替换发型",
    "alternate_color": "替换配色",
    "cosplay": "角色扮演",
    "parody": "戏仿",
    "crossover": "跨作品联动",
    "genderswap": "性别转换",
    "personification": "拟人化",
    "anthropomorphism": "拟人化",
    "mecha": "机甲",
    "robot": "机器人",
    "cyborg": "赛博格",
    "vampire": "吸血鬼",
    "witch": "女巫",
    "elf": "精灵",
    "demon": "恶魔",
    "angel": "天使",
    "fairy": "仙女",
    "mermaid": "美人鱼",
    "princess": "公主",
    "knight": "骑士",
    "samurai": "武士",
    "ninja": "忍者",
    "pirate": "海盗",
    "idol": "偶像",
    "magical_girl": "魔法少女",
    "school_girl": "女学生",

    # === 色彩标签 ===
    "red": "红色",
    "blue": "蓝色",
    "green": "绿色",
    "yellow": "黄色",
    "purple": "紫色",
    "pink": "粉色",
    "orange": "橙色",
    "brown": "棕色",
    "black": "黑色",
    "white": "白色",
    "golden": "金色",
    "silver": "银色",

    # === 季节/节日 ===
    "christmas": "圣诞节",
    "halloween": "万圣节",
    "valentine": "情人节",
    "new_year": "新年",
    "birthday": "生日",
    "wedding": "婚礼",
    "spring": "春天",
    "summer": "夏天",
    "autumn": "秋天",
    "fall": "秋天",
    "winter": "冬天",
    "fireworks": "烟花",
    "jack-o'-lantern": "南瓜灯",
    "pumpkin": "南瓜",
    "santa_costume": "圣诞装",
    "santa_hat": "圣诞帽",

    # === 场景/状态补充 ===
    "submerged": "浸入水中",
    "partially_submerged": "部分浸水",
    "wet": "湿润",
    "wet_clothes": "湿衣服",
    "wind": "风",
    "windy": "有风",
    "hair_blowing": "头发飘动",
    "falling": "坠落",
    "falling_petals": "飘落花瓣",
    "blood": "血",
    "fire": "火焰",
    "ice": "冰",
    "electricity": "电",
    "magic": "魔法",
    "magic_circle": "魔法阵",
    "aura": "气场",
    "steam": "蒸汽",
    "smoke": "烟雾",
    "fog": "雾",
    "mist": "薄雾",
    "dust": "灰尘",
    "explosion": "爆炸",
    "splash": "水花",
    "splashing": "溅水",
    "ripples": "涟漪",
    "waves": "波浪",
    "wave": "波浪",
    "star_(symbol)": "星形符号",
    "heart": "爱心",
    "musical_note": "音符",
    "spoken_heart": "说爱心",
    "swirl": "漩涡",
    "symbol": "符号",
    "exclamation_mark": "感叹号",
    "question_mark": "问号",
    "ellipsis": "省略号",
    "zzz": "睡觉",
    "spoken_ellipsis": "说省略号",
    "trembling": "颤抖",
    "motion": "运动",
    "speed": "速度",
    "silhouette": "剪影",
    "shadow": "影子",
    "scenery": "风景",
    "landscape": "风景画",
    "horizon": "地平线",
    "aurora": "极光",
    "rainbow": "彩虹",
    "lightning": "闪电",
    "thunder": "雷电",
    "snowflakes": "雪花",
    "leaf": "叶子",
    "leaves": "树叶",
    "autumn_leaves": "红叶",
    "maple_leaf": "枫叶",
    "clover": "三叶草",
    "feathers": "羽毛",
    "feather": "羽毛",
    "fur": "皮毛",
    "fur_trim": "毛边",
    "fur_collar": "毛领",
    "hood": "兜帽",
    "hood_up": "戴兜帽",
    "hood_down": "放下兜帽",
    "eye_contact": "对视",
    "nose": "鼻子",
    "lips": "嘴唇",
    "eyelashes": "睫毛",
    "eyebrows": "眉毛",
    "forehead": "额头",
    "neck": "脖子",
    "shoulder": "肩膀",
    "waist": "腰",
    "hip": "臀",
    "knee": "膝盖",
    "elbow": "手肘",
    "wrist": "手腕",
    "finger": "手指",
    "fingernails": "指甲",
    "nail_polish": "指甲油",
    "hair_intakes": "进气口发型",
    "two_side_up": "双侧上扎",
    "one_side_up": "单侧上扎",
    "updo": "盘发",
    "topknot": "顶髻",
    "very_short_hair": "极短发",
    "shiny_hair": "有光泽的头发",
    "hair_over_shoulder": "头发搭在肩上",
    "hair_behind_ear": "耳后发",
    "eyepatch": "眼罩",
    "blindfold": "蒙眼",
    "veil": "面纱",
    "bandage": "绷带",
    "bandages": "绷带",
    "bandaid": "创可贴",
    "sash": "腰带",
    "obi": "腰封",
    "corsage": "胸花",
    "brooch": "胸针",
    "pendant": "吊坠",
    "cross": "十字架",
    "gem": "宝石",
    "jewel": "珠宝",
    "jewelry": "首饰",
    "cuffs": "袖口",
    "wristband": "腕带",
    "armband": "臂环",
    "armlet": "臂环",
    "shoulder_armor": "肩甲",
    "gauntlets": "护手",
    "pauldrons": "肩甲",
    "breastplate": "胸甲",
    "helmet": "头盔",
    "visor": "面罩",
    "leotard": "紧身衣",
    "bodysuit": "紧身连体衣",
    "catsuit": "猫女装",
    "jumpsuit": "连体服",
    "overalls": "工装裤",
    "jeans": "牛仔裤",
    "denim": "牛仔布",
    "gym_uniform": "体操服",
    "track_suit": "运动套装",
    "sports_bra": "运动内衣",
    "jersey": "球衣",
    "lab_coat": "白大褂",
    "nurse": "护士",
    "nurse_cap": "护士帽",
    "police": "警察",
    "detective": "侦探",
    "chef": "厨师",
    "butler": "管家",
    "formal": "正装",
    "casual": "休闲装",
    "winter_clothes": "冬装",
    "summer_dress": "夏装裙",
    "sundress": "太阳裙",
    "nightgown": "睡裙",
    "pajamas": "睡衣",
    "bathrobe": "浴袍",
    "towel": "毛巾",
    "naked_towel": "裹毛巾",
    "partially_undressed": "半脱",
    "undressing": "脱衣",
    "adjusted_clothing": "整理衣服",
    "tying_hair": "扎头发",
    "adjusting_hair": "整理头发",
    "brushing_hair": "梳头",
    "covering_mouth": "捂嘴",
    "covering_face": "捂脸",
    "hand_in_hair": "手插头发",
    "hands_in_pockets": "手插口袋",
    "hands_behind_back": "背手",
    "hands_behind_head": "双手抱头",
    "hands_together": "双手合十",
    "hands_clasped": "双手紧握",
    "interlocked_fingers": "十指交叉",
    "pointing": "指向",
    "pointing_at_viewer": "指向观众",
    "pointing_up": "手指向上",
    "finger_to_mouth": "手指放嘴边",
    "shushing": "嘘",
    "beckoning": "招手",
    "clenched_hand": "握拳",
    "clenched_hands": "双拳紧握",
    "fist": "拳头",
    "open_hand": "张开手掌",
    "outstretched_hand": "伸出手",
    "outstretched_arm": "伸出手臂",
    "outstretched_arms": "张开双臂",
    "own_hands_together": "双手合拢",
    "praying": "祈祷",
    "heart_hands": "比心",
    "cat_pose": "猫咪姿势",
    "arched_back": "弓背",
    "bent_over": "弯腰",
    "head_down": "低头",
    "head_back": "仰头",
    "looking_at_another": "看着另一个人",
    "staring": "凝视",
    "glaring": "怒视",
    "eye_closed": "闭眼",
    "konijn": "兔子",

    # === 常见组合标签 ===
    "black_gloves": "黑色手套",
    "white_gloves": "白色手套",
    "black_bow": "黑色蝴蝶结",
    "red_bow": "红色蝴蝶结",
    "blue_bow": "蓝色蝴蝶结",
    "white_bow": "白色蝴蝶结",
    "red_ribbon": "红色丝带",
    "black_ribbon": "黑色丝带",
    "blue_ribbon": "蓝色丝带",
    "white_ribbon": "白色丝带",
    "blue_sky": "蓝天",
    "red_flower": "红花",
    "white_flower": "白花",
    "blue_flower": "蓝花",
    "pink_flower": "粉花",
    "yellow_flower": "黄花",
    "black_skirt": "黑色裙子",
    "white_skirt": "白色裙子",
    "blue_skirt": "蓝色裙子",
    "black_jacket": "黑色夹克",
    "brown_jacket": "棕色夹克",
    "white_jacket": "白色夹克",
    "black_pants": "黑色裤子",
    "black_footwear": "黑色鞋子",
    "brown_footwear": "棕色鞋子",
    "white_footwear": "白色鞋子",
    "black_legwear": "黑色袜子",
    "white_legwear": "白色袜子",
    "black_headwear": "黑色帽子",
    "red_headwear": "红色帽子",
    "black_choker": "黑色项圈",
    "black_necktie": "黑色领带",
    "red_necktie": "红色领带",
    "blue_necktie": "蓝色领带",
    "black_bowtie": "黑色领结",
    "red_bowtie": "红色领结",
    "black_cape": "黑色披风",
    "red_cape": "红色披风",
    "white_cape": "白色披风",
}


class TagTranslator:
    """标签翻译器（重构版）"""
    
    def __init__(self, 
                 translation_file: str = "models/deepdanbooru/tag_translations.json",
                 cache_file: str = "models/deepdanbooru/tag_cache.json"):
        """
        初始化标签翻译器
        
        翻译优先级：内建字典 > 外部翻译文件 > 缓存 > 规则推导 > 保留原文
        """
        self.translation_file = translation_file
        self.cache_file = cache_file

        # 外部翻译文件
        self.ext_translations: Dict[str, str] = {}
        # 运行时缓存（新翻译会写入）
        self.cache: Dict[str, str] = {}
        
        self._load_ext_translations()
        self._load_cache()
    
    def _load_ext_translations(self):
        """加载外部翻译文件（作为内建字典的补充）"""
        if os.path.exists(self.translation_file):
            try:
                with open(self.translation_file, 'r', encoding='utf-8') as f:
                    self.ext_translations = json.load(f)
                logger.info(f"成功加载 {len(self.ext_translations)} 个外部翻译")
            except Exception as e:
                logger.error(f"加载外部翻译失败: {e}")
        else:
            logger.info("外部翻译文件不存在，仅使用内建字典")

    def _load_cache(self):
        """加载翻译缓存"""
        if os.path.exists(self.cache_file):
            try:
                with open(self.cache_file, 'r', encoding='utf-8') as f:
                    raw = json.load(f)
                # 过滤掉缓存中无效的翻译（值 == 键 说明没翻译成功）
                self.cache = {k: v for k, v in raw.items() 
                              if v and v != k and not self._is_garbage(v)}
                logger.info(f"成功加载 {len(self.cache)} 个有效缓存翻译")
            except Exception as e:
                logger.error(f"加载缓存失败: {e}")
    
    def _save_cache(self):
        """保存缓存"""
        try:
            os.makedirs(os.path.dirname(self.cache_file), exist_ok=True)
            with open(self.cache_file, 'w', encoding='utf-8') as f:
                json.dump(self.cache, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"保存缓存失败: {e}")

    @staticmethod
    def _is_garbage(text: str) -> bool:
        """检查翻译结果是否是垃圾（纯符号/数字/单字符）"""
        stripped = text.strip()
        if not stripped:
            return True
        if all(c in '?!.#@*&^%$~=+|\\/<>[]{}()0123456789_- ' for c in stripped):
            return True
        return False

    def translate(self, english_tag: str) -> str:
        """
        将英文标签翻译为中文
        
        优先级：
        1. 内建字典（400+ 高质量翻译）
        2. 外部翻译文件
        3. 本地缓存
        4. 规则推导（颜色+特征组合）
        5. 保留原文
        """
        tag = english_tag.strip().lower()
        
        # 1. 内建字典（最高优先级，覆盖最广）
        if tag in BUILTIN_TRANSLATIONS:
            return BUILTIN_TRANSLATIONS[tag]
        
        # 2. 外部翻译文件
        if tag in self.ext_translations:
            val = self.ext_translations[tag]
            if val and val != tag:
                return val
        
        # 3. 本地缓存
        if tag in self.cache:
            return self.cache[tag]
        
        # 4. 规则推导
        rule_result = self._apply_rules(tag)
        if rule_result != tag:
            self.cache[tag] = rule_result
            self._save_cache()
            return rule_result
        
        # 5. 保留原文
        return english_tag

    def _apply_rules(self, tag: str) -> str:
        """
        基于规则的翻译推导
        
        处理颜色+特征组合和其他模式
        """
        COLOR_MAP = {
            'blue': '蓝色', 'red': '红色', 'green': '绿色',
            'yellow': '黄色', 'purple': '紫色', 'pink': '粉色',
            'orange': '橙色', 'brown': '棕色', 'black': '黑色',
            'white': '白色', 'grey': '灰色', 'gray': '灰色',
            'blonde': '金色', 'silver': '银色', 'golden': '金色',
            'dark': '深色', 'light': '浅色', 'aqua': '水蓝色',
        }
        
        FEATURE_MAP = {
            'hair': '头发', 'eyes': '眼睛', 'dress': '连衣裙',
            'shirt': '衬衫', 'skirt': '裙子', 'bow': '蝴蝶结',
            'ribbon': '丝带', 'scarf': '围巾', 'hat': '帽子',
            'gloves': '手套', 'socks': '短袜', 'jacket': '夹克',
            'pants': '裤子', 'shorts': '短裤', 'coat': '外套',
            'cape': '披风', 'wings': '翅膀', 'horns': '角',
            'tail': '尾巴', 'nails': '指甲', 'flower': '花',
            'footwear': '鞋子', 'legwear': '袜子', 'headwear': '帽子',
            'neckwear': '颈饰', 'swimsuit': '泳装', 'bikini': '比基尼',
            'necktie': '领带', 'bowtie': '领结', 'choker': '项圈',
            'thighhighs': '过膝袜', 'kneehighs': '及膝袜',
            'background': '背景', 'sky': '天空', 'fire': '火',
            'skin': '肌肤', 'earrings': '耳环', 'armor': '盔甲',
        }
        
        # 尝试匹配 颜色_特征 模式
        parts = tag.split('_', 1)
        if len(parts) == 2:
            color_en, feature_en = parts
            if color_en in COLOR_MAP and feature_en in FEATURE_MAP:
                return COLOR_MAP[color_en] + FEATURE_MAP[feature_en]
        
        # 尝试匹配 特征_颜色 模式（如 hair_blue 虽然少见但可能出现）
        if len(parts) == 2:
            feature_en, color_en = parts
            if color_en in COLOR_MAP and feature_en in FEATURE_MAP:
                return COLOR_MAP[color_en] + FEATURE_MAP[feature_en]
        
        return tag

    def translate_batch(self, tags: list) -> list:
        """批量翻译标签"""
        return [self.translate(tag) for tag in tags]

    def get_translation_stats(self) -> dict:
        """获取翻译统计"""
        return {
            "builtin_translations": len(BUILTIN_TRANSLATIONS),
            "ext_translations": len(self.ext_translations),
            "cached_translations": len(self.cache),
            "total_translations": len(BUILTIN_TRANSLATIONS) + len(self.ext_translations) + len(self.cache),
        }


# 全局翻译器实例
_translator: Optional[TagTranslator] = None


def get_translator() -> TagTranslator:
    """获取全局翻译器实例"""
    global _translator
    if _translator is None:
        _translator = TagTranslator()
    return _translator

